Feature:RBI

Background:
	Given I navigate to mifos using "default#/"
	And I login into mifos site using "Login" excel sheet
		|Login.xlsx|
	Then I should see logged in successfully  

@4061-CREATECLIENT-SUBMITNEWLOAN-CLOSECLIENT
Scenario:4061-CREATECLIENT-SUBMITNEWLOAN-CLOSECLIENT
      Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4061-CREATECLIENT-SUBMITNEWLOAN-CLOSECLIENT.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4061-CREATECLIENT-SUBMITNEWLOAN-CLOSECLIENT.xlsx|
	  Then I "Close Client" from "Close Client" sheet	
				|4061-CREATECLIENT-SUBMITNEWLOAN-CLOSECLIENT.xlsx|
				
@4062-CREATECLIENT-DISBURSELOAN-CLOSECLIENT
Scenario:4062-CREATECLIENT-DISBURSELOAN-CLOSECLIENT
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4062-CREATECLIENT-DISBURSELOAN-CLOSECLIENT.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4062-CREATECLIENT-DISBURSELOAN-CLOSECLIENT.xlsx|
	  Then I "Close Client" from "Close Client" sheet	
				|4062-CREATECLIENT-DISBURSELOAN-CLOSECLIENT.xlsx|
				
@4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT
Scenario:4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT.xlsx|
	  Then I "WRITEOFF" and verified the following tabs
	            |4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT.xlsx|
	  Then I "Close Client" from "Close Client" sheet	
				|4063-CREATECLIENT-DISBURSELOAN-WRITEOFFLOAN-CLOSECLIENT.xlsx|
				
@4064-CREATECLIENT-APPROVELOAN-CLOSECLIENT
Scenario:4064-CREATECLIENT-APPROVELOAN-CLOSECLIENT
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4064-CREATECLIENT-APPROVELOAN-CLOSECLIENT.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4064-CREATECLIENT-APPROVELOAN-CLOSECLIENT.xlsx|
	  Then I "Close Client" from "Close Client" sheet	
				|4064-CREATECLIENT-APPROVELOAN-CLOSECLIENT.xlsx|
				
@4065-CREATECLIENT-ACTIATESAVINGS-CLOSECLIENT
	  Scenario:4065-CREATECLIENT-ACTIATESAVINGS-CLOSECLIENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4065-CREATECLIENT-ACTIATESAVINGS-CLOSECLIENT.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4065-CREATECLIENT-ACTIATESAVINGS-CLOSECLIENT.xlsx|
	 
@4067-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE
	  Scenario:4067-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4067-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4067-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4067-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|

@4068-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE
	  Scenario:4068-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4068-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4068-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE.xlsx|	 	 

@4069-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE
	  Scenario:4069-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4069-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4069-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4069-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|
	 
@4070-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-PAYCLIENTCHARGE
	  Scenario:4070-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-PAYCLIENTCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4070-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4070-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4070-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|
	 
@4071-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-WAIVECLIENTCHARGE
	  Scenario:4071-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-WAIVECLIENTCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4071-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-WAIVECLIENTCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4071-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-CLOSECLIENT-WAIVECLIENTCHARGE.xlsx|
	 
@4072-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE
	  Scenario:4072-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4072-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4072-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4072-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-PAYCHARGE.xlsx|

@4073-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE
	  Scenario:4073-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4073-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4073-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-WAIVECHARGE.xlsx|	 	 

@4074-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE
	  Scenario:4074-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4074-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4074-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4074-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CHARGESOVERVIEW-CLICKCHARGE-DELETECHARGE.xlsx|
	 
@4075-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-PAYCLIENTCHARGE
	  Scenario:4075-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-PAYCLIENTCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4075-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4075-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|	 	 
Then i validate and Verify from "Output" sheet
	 |4075-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-PAYCLIENTCHARGE.xlsx|
	 
@4076-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-WAIVECLIENTCHARGE
	  Scenario:4076-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-WAIVECLIENTCHARGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4076-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-WAIVECLIENTCHARGE.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4076-CREATEACTIVECLIENT-PERSON-ADD-CLIENTCHARGE-SP-PENALTY-CLOSECLIENT-WAIVECLIENTCHARGE.xlsx|	 
	 
@4077-CREATEACTIVECLIENT-PERSON-CLOSECLIENT-REACTIVATECLIENT
	  Scenario:4077-CREATEACTIVECLIENT-PERSON-CLOSECLIENT-REACTIVATECLIENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4077-CREATEACTIVECLIENT-PERSON-CLOSECLIENT-REACTIVATECLIENT.xlsx|
Then I "Apply Charge and Pay Charge" from "Client Charge" sheet
	 |4077-CREATEACTIVECLIENT-PERSON-CLOSECLIENT-REACTIVATECLIENT.xlsx|	 	
	 
@4078-CREATEACTIVECLIENT-UPLOADCLIENTIMAGE
	  Scenario:4078-CREATEACTIVECLIENT-UPLOADCLIENTIMAGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4078-CREATEACTIVECLIENT-UPLOADCLIENTIMAGE.xlsx|
Then I "UPLOAD CLIENT IMAGE" from "UPLOAD" sheet
	 |4078-CREATEACTIVECLIENT-UPLOADCLIENTIMAGE.xlsx|		
	 
@4079-CREATEACTIVECLIENT-CAPTURECLIENTIMAGE
	  Scenario:4079-CREATEACTIVECLIENT-CAPTURECLIENTIMAGE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4079-CREATEACTIVECLIENT-CAPTURECLIENTIMAGE.xlsx|
Then I "UPLOAD CLIENT IMAGE" from "UPLOAD" sheet
	 |4079-CREATEACTIVECLIENT-CAPTURECLIENTIMAGE.xlsx|
	 
@4080-CREATEACTIVECLIENT-UPLOADCLIENTSIGNATURE
	  Scenario:4080-CREATEACTIVECLIENT-UPLOADCLIENTSIGNATURE 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4080-CREATEACTIVECLIENT-UPLOADCLIENTSIGNATURE.xlsx|
Then I "UPLOAD CLIENT SIGNATURE" from "UPLOAD" sheet
	 |4080-CREATEACTIVECLIENT-UPLOADCLIENTSIGNATURE.xlsx|	
	 
@4081-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT
	  Scenario:4081-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4081-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT.xlsx|
Then I "UPLOAD CLIENT IDENTITY" from "UPLOAD" sheet
	 |4081-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT.xlsx|
Then i validate and Verify from "Output" sheet
	 |4081-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT.xlsx|
	 
@4082-CREATEACTIVECLIENT-DELETECLIENT-IDENTITY-DOCUMENT
	  Scenario:4082-CREATEACTIVECLIENT-DELETECLIENT-IDENTITY-DOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4082-CREATEACTIVECLIENT-DELETECLIENT-IDENTITY-DOCUMENT.xlsx|
Then I "UPLOAD CLIENT IDENTITY" from "UPLOAD" sheet
	 |4082-CREATEACTIVECLIENT-DELETECLIENT-IDENTITY-DOCUMENT.xlsx|
Then i validate and Verify from "Output" sheet
	 |4082-CREATEACTIVECLIENT-DELETECLIENT-IDENTITY-DOCUMENT.xlsx|	 
	 
@4083-CREATEACTIVECLIENT-UPLOADCLIENT-Duplicate-IDENTITY-DOCUMENT
	  Scenario:4083-CREATEACTIVECLIENT-UPLOADCLIENT-Duplicate-IDENTITY-DOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4083-CREATEACTIVECLIENT-UPLOADCLIENT-Duplicate-IDENTITY-DOCUMENT.xlsx|
Then I "UPLOAD CLIENT IDENTITY" from "UPLOAD" sheet
	 |4083-CREATEACTIVECLIENT-UPLOADCLIENT-Duplicate-IDENTITY-DOCUMENT.xlsx|
	 
@4084-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT-ADDCLIENT-IDENTITY
	  Scenario:4084-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT-ADDCLIENT-IDENTITY 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4084-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT-ADDCLIENT-IDENTITY.xlsx|
Then I "UPLOAD CLIENT IDENTITY" from "UPLOAD" sheet
	 |4084-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT-ADDCLIENT-IDENTITY.xlsx|
Then i validate and Verify from "Output" sheet
	 |4084-CREATEACTIVECLIENT-UPLOADCLIENT-IDENTITY-DOCUMENT-ADDCLIENT-IDENTITY.xlsx|
	 
@4085-CREATEACTIVECLIENT-UPLOADCLIENT-DOCUMENT
	  Scenario:4085-CREATEACTIVECLIENT-UPLOADCLIENT-DOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4085-CREATEACTIVECLIENT-UPLOADCLIENT-DOCUMENT.xlsx|
Then I "UPLOAD CLIENT DOCUMENT" from "UPLOAD" sheet
	 |4085-CREATEACTIVECLIENT-UPLOADCLIENT-DOCUMENT.xlsx|
Then i validate and Verify from "Output" sheet
	 |4085-CREATEACTIVECLIENT-UPLOADCLIENT-DOCUMENT.xlsx|	 

@4086-CREATEACTIVECLIENT-DOWNLOAD-CLIENT-DOCUMENT
	  Scenario:4086-CREATEACTIVECLIENT-DOWNLOAD-CLIENT-DOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4086-CREATEACTIVECLIENT-DOWNLOAD-CLIENT-DOCUMENT.xlsx|
Then I "UPLOAD CLIENT DOCUMENT" from "UPLOAD" sheet
	 |4086-CREATEACTIVECLIENT-DOWNLOAD-CLIENT-DOCUMENT.xlsx|
Then i validate and Verify from "Output" sheet
	 |4086-CREATEACTIVECLIENT-DOWNLOAD-CLIENT-DOCUMENT.xlsx|
	 	 
@4087-CREATEACTIVECLIENT-DELETE-CLIENTDOCUMENT
	  Scenario:4087-CREATEACTIVECLIENT-DELETE-CLIENTDOCUMENT 
Given I setup the clients 
Then I entered the values into client from "Input" sheet
	 |4087-CREATEACTIVECLIENT-DELETE-CLIENTDOCUMENT.xlsx|
Then I "UPLOAD CLIENT DOCUMENT" from "UPLOAD" sheet
	 |4087-CREATEACTIVECLIENT-DELETE-CLIENTDOCUMENT.xlsx|
Then i validate and Verify from "Output" sheet
	 |4087-CREATEACTIVECLIENT-DELETE-CLIENTDOCUMENT.xlsx|
######	 
				
				
@4088-CREATEACTIVECLIENT-ADDNOTES
Scenario:4088-CREATEACTIVECLIENT-ADDNOTES
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4088-CREATEACTIVECLIENT-ADDNOTES.xlsx|
	  Then I "addnotes" from "AddNotes" sheet
	  			|4088-CREATEACTIVECLIENT-ADDNOTES.xlsx|
	  Then i validate and Verify from "Output" sheet
                |4088-CREATEACTIVECLIENT-ADDNOTES.xlsx|  
                

@4089-CREATEACTIVECLIENT-DISBURSE2LOANS
Scenario:4089-CREATEACTIVECLIENT-DISBURSE2LOANS
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4089-CREATEACTIVECLIENT-DISBURSE2LOANS.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4089-CREATEACTIVECLIENT-DISBURSE2LOANS.xlsx|
	  When I set up the new create loan from "NewLoanInput1" sheet
	  			|4089-CREATEACTIVECLIENT-DISBURSE2LOANS.xlsx|
	  			
@4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN
Scenario:4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN
     Given I setup the clients
	  When I entered the values into client from "Input" sheet
	  			|4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN.xlsx|
	  When I set up the new create loan from "NewLoanInput" sheet
	  			|4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN.xlsx|
	  When I set up the new create loan from "NewLoanInput2" sheet
	  			|4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN.xlsx|
	  			 Then I "Close Client" from "Close Client" sheet	
				|4090-CREATEACTIVECLIENT-DISBURSE2LOANS-CLOSE1LOAN.xlsx|	 
				
@4091-CREATGROUP-WITHOUTCLIENTATTACHED
Scenario:4091-CREATGROUP-WITHOUTCLIENTATTACHED
      Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4091-CREATGROUP-WITHOUTCLIENTATTACHED.xlsx|
		  			
@4092-CREATGROUP-WITHOUTCLIENTATTACHED-ACTIVE
Scenario:4092-CREATGROUP-WITHOUTCLIENTATTACHED-ACTIVE
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4092-CREATGROUP-WITHOUTCLIENTATTACHED-ACTIVE.xlsx|	  	
	  			
@4093-CREATGROUP-WITHCLIENTATTACHED
Scenario:4093-CREATGROUP-WITHCLIENTATTACHED
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4093-CREATGROUP-WITHCLIENTATTACHED.xlsx|		  									 
	 
@4094-CREATEGROUP-WITHOUTCLIENTATTACHED-ASSIGNSTAFF
Scenario:4094-CREATEGROUP-WITHOUTCLIENTATTACHED-ASSIGNSTAFF
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4094-CREATEGROUP-WITHOUTCLIENTATTACHED-ASSIGNSTAFF.xlsx|
	  			
@4095-CREATEGROUP-WITHOUTCLIENTATTACHED-UNASSIGNSTAFF
Scenario:4095-CREATEGROUP-WITHOUTCLIENTATTACHED-UNASSIGNSTAFF
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4095-CREATEGROUP-WITHOUTCLIENTATTACHED-UNASSIGNSTAFF.xlsx|	
	  			
@4096-CREATEGROUP-WITHOUTCLIENTATTACHED-EDIT
Scenario:4096-CREATEGROUP-WITHOUTCLIENTATTACHED-EDIT
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4096-CREATEGROUP-WITHOUTCLIENTATTACHED-EDIT.xlsx|	
	  			
@4097-CREATEGROUP-WITHOUTCLIENTATTACHED-DELETE
Scenario:4097-CREATEGROUP-WITHOUTCLIENTATTACHED-DELETE
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4097-CREATEGROUP-WITHOUTCLIENTATTACHED-DELETE.xlsx|
	  			
@4098-CREATEGROUP-WITHOUTCLIENTATTACHED-CLOSE
Scenario:4098-CREATEGROUP-WITHOUTCLIENTATTACHED-CLOSE
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4098-CREATEGROUP-WITHOUTCLIENTATTACHED-CLOSE.xlsx|	  
	  			
@4099-CREATACTIVEGROUP-CLOSEGROUP
Scenario:4099-CREATACTIVEGROUP-CLOSEGROUP
     Given I setup the group
	  When I entered the values into group from "Input" sheet
	  			|4099-CREATACTIVEGROUP-CLOSEGROUP.xlsx|		  			
	  			

@4100-CREATACTIVEGROUP-ATTACHEMEETING
Scenario:4100-CREATACTIVEGROUP-ATTACHEMEETING
     Given I setup the group
   When I entered the values into group from "Input" sheet
      |4100-CREATACTIVEGROUP-ATTACHEMEETING.xlsx|	  							
	  			
@4101-CREATACTIVEGROUP-EDIT
Scenario:4101-CREATACTIVEGROUP-EDIT
     Given I setup the group
   When I entered the values into group from "Input" sheet
      |4101-CREATACTIVEGROUP-EDIT.xlsx|	  			
	  				  				  			  					 
	 